### ISSUE TITLE
Search on the home page doesn't work

### ISSUE THREAD

**Issue by ttasovac** [DARIAH-ERIC/dariah-campus#1416]
Searching is currently possible only from https://campus.dariah.eu/search but not from the main page.

**Comment by babslgam** [comment]
hi toma,
this should work now.

**Comment by ttasovac** [comment]
Thanks, Barbara. What we're still missing is the autocomplete dropdown on the search field, which is what we had in the previous version and what our users expect to see.

**Comment by stefanprobst** [comment]
what do you mean? the previous search opened a dialog overlay, where search results were listed. we now have a dedicated search page instead of an overlay where search results are listed.

**Comment by stefanprobst** [comment]
btw i have deployed the original dariah campus here: https://dariah-campus-original.vercel.app/ which may be helpful to check out while we are finishing the transition.

**Comment by ttasovac** [comment]
ah, very good to be reminded.

Yes, you are aboslutely right, we had a dialog overlay, not a dropdown. But the problem for me is that we used to have instant results either way from the home page and now we don't. Because i was used to the instant search in an overlay, I typed "xml" and when nothing happened, I assumed the search was not working at all. We are now expected to click enter to be moved to the search page —  that won't be clear to any user. 

We could add a submit button on the landing page or do a JS redirect on click within the input field that will automatically take the user to the search page and let him continue from there. What do you think?

**Comment by stefanprobst** [comment]
yes we can add a submit button to make it more clear!

**Comment by babslgam** [comment]
can we have that as a separate feature request issue, please?
because technically this issue is solved.

**Comment by stefanprobst** [comment]
continued in #1419
